sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  # Build the docker image
  - docker build -t cactus_app/cactus-app-client-service .
  - docker images
install:
  - docker run -ti --name=cactus_app_client -d -e CODECOV_TOKEN=$CODECOV_TOKEN -v $(pwd):/app -p 3000:3000 cactus_app/cactus-app-client-service
  - docker ps -a

script:
  # Wait for a minute to give time for the container to start properly
  - sleep 1m
  # Run the normal test processes
  - docker exec -ti cactus_app_client yarn test
after_success: docker exec -ti cactus_app_client yarn coverage